# Generated by Django 4.2.10 on 2026-06-01 06:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('temperature', 'High Temperature'), ('pressure', 'High Pressure'), ('vibration', 'High Vibration'), ('smoke', 'Smoke/Gas Detected'), ('signal_loss', 'Signal Loss'), ('route_deviation', 'Route Deviation'), ('restricted_zone', 'Restricted Zone Entry'), ('sensor_failure', 'Sensor Failure'), ('speed', 'Speed Violation')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trains.train')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['train', '-timestamp'], name='alerts_train_i_f3294c_idx'), models.Index(fields=['severity', 'is_resolved'], name='alerts_severit_ff8e8f_idx')],
            },
        ),
    ]
