# Generated by Django 4.2.10 on 2026-06-01 06:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFenceZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('restricted', 'Restricted Zone'), ('maintenance', 'Maintenance Area'), ('hazard', 'Hazard Zone')], max_length=20)),
                ('boundary', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'geofence_zones',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waypoints', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('train', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='trains.train')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
    ]
