# Generated by Django 4.2.10 on 2026-06-04 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('inspection', 'Routine Inspection'), ('repair', 'Repair'), ('replacement', 'Parts Replacement'), ('calibration', 'Sensor Calibration'), ('emergency', 'Emergency Fix'), ('preventive', 'Preventive Maintenance')], default='inspection', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='open', max_length=15)),
                ('issue_description', models.TextField()),
                ('work_done', models.TextField(blank=True, default='')),
                ('parts_used', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_logs', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_logs', to=settings.AUTH_USER_MODEL)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='trains.train')),
            ],
            options={
                'db_table': 'maintenance_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['train', '-created_at'], name='maintenance_train_i_75c0ab_idx'), models.Index(fields=['status', 'priority'], name='maintenance_status_23c5e0_idx')],
            },
        ),
    ]
