# Generated by Django 4.2.10 on 2026-06-01 06:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('vibration', models.FloatField()),
                ('smoke', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical'), ('offline', 'Offline')], default='normal', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='trains.train')),
            ],
            options={
                'db_table': 'sensor_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['train', '-timestamp'], name='sensor_data_train_i_ebda56_idx'), models.Index(fields=['-timestamp'], name='sensor_data_timesta_ac587d_idx')],
            },
        ),
        migrations.CreateModel(
            name='GPSHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_history', to='trains.train')),
            ],
            options={
                'db_table': 'gps_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['train', '-timestamp'], name='gps_history_train_i_a6f212_idx')],
            },
        ),
    ]
